### ISSUE TITLE
Add Workspace Rename to Initial Deploy Setup Steps

### ISSUE THREAD

**Issue by jeremy-farrance** [Accuraty/AccuTheme#72]
To prevent the confusing and complicated issues that arise in VS Code when you merge in commits that rename the 'ABBV20xx.code-workspace' file, we need to insure that this step is taken care of during the initial setup.

For example, when deploying PDPR2023 using AccuTheme-*, make sure file noted above gets renamed to `PDPR2023.code-workspace`. 
 
It might even make sense to do this step first, immediately after copying from the template to the new repo - and doing it on GitHub, in the browser, as a direct commit on the Main branch.

**Comment by jtherrien-accuraty** [comment]
Added as part of the creating the new repo steps
